from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
            ('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),
            ('name',models.CharField(max_length=120)),('name_hi',models.CharField(blank=True,max_length=120)),('slug',models.SlugField(blank=True,max_length=140,unique=True)),('description',models.TextField(blank=True)),('description_hi',models.TextField(blank=True)),('sort_order',models.PositiveIntegerField(default=0)),('published',models.BooleanField(default=True)),
            ('parent',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='children',to='showroom.category')),
        ],options={'ordering':['sort_order','name'],'verbose_name_plural':'Categories'}),
        migrations.CreateModel(name='Customer', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('mobile',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('address',models.TextField(blank=True)),('notes',models.TextField(blank=True))]),
        migrations.CreateModel(name='Supplier', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=180)),('mobile',models.CharField(blank=True,max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('address',models.TextField(blank=True)),('gstin',models.CharField(blank=True,max_length=30)),('notes',models.TextField(blank=True))]),
        migrations.CreateModel(name='SiteSetting', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('business_name',models.CharField(default='Akshat Agni EV Motors',max_length=180)),('tagline',models.CharField(default='Shubh Shuruaat, Agni ki Raftaar',max_length=250)),('tagline_hi',models.CharField(default='शुभ शुरुआत, अग्नि की रफ्तार',max_length=250)),('phone_primary',models.CharField(default='9425969464',max_length=30)),('phone_secondary',models.CharField(default='7974281559',max_length=30)),('address',models.TextField(default='Maihar, Madhya Pradesh')),('address_hi',models.TextField(default='मैहर, मध्य प्रदेश')),('whatsapp',models.CharField(default='9425969464',max_length=30)),('about',models.TextField(blank=True)),('about_hi',models.TextField(blank=True)),('hero_title',models.CharField(default='Electric mobility, made simple.',max_length=220)),('hero_title_hi',models.CharField(default='इलेक्ट्रिक मोबिलिटी, अब आसान।',max_length=220)),('hero_subtitle',models.TextField(blank=True)),('hero_subtitle_hi',models.TextField(blank=True)),('hero_image_data',models.TextField(blank=True)),('logo_data',models.TextField(blank=True))]),
        migrations.CreateModel(name='Product', fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=180)),('name_hi',models.CharField(blank=True,max_length=180)),('slug',models.SlugField(blank=True,max_length=200,unique=True)),('segment',models.CharField(blank=True,help_text='Example: Single Light, Double Light, High Range, City Ride',max_length=100)),('short_description',models.CharField(blank=True,max_length=250)),('short_description_hi',models.CharField(blank=True,max_length=250)),('description',models.TextField(blank=True)),('description_hi',models.TextField(blank=True)),('price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('offer_price',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('cost_price',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('stock',models.PositiveIntegerField(default=0)),('featured',models.BooleanField(default=False)),('published',models.BooleanField(default=True)),('coming_soon',models.BooleanField(default=False)),('image_data',models.TextField(blank=True)),('sku',models.CharField(blank=True,max_length=60)),('battery',models.CharField(blank=True,max_length=120)),('range_text',models.CharField(blank=True,max_length=120)),('warranty',models.CharField(blank=True,max_length=120)),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='products',to='showroom.category')),
        ],options={'ordering':['-featured','name']}),
        migrations.CreateModel(name='ProductGallery', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('caption',models.CharField(blank=True,max_length=150)),('image_data',models.TextField()),('sort_order',models.PositiveIntegerField(default=0)),('published',models.BooleanField(default=True)),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='gallery',to='showroom.product'))]),
        migrations.CreateModel(name='GalleryImage', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('title_hi',models.CharField(blank=True,max_length=180)),('description',models.TextField(blank=True)),('description_hi',models.TextField(blank=True)),('category',models.CharField(choices=[('SHOWROOM','Showroom'),('OPENING','Opening'),('EVENT','Event'),('DELIVERY','Customer Delivery'),('OFFER','Offer'),('SERVICE','Service'),('OTHER','Other')],default='SHOWROOM',max_length=30)),('image_data',models.TextField()),('published',models.BooleanField(default=True)),('featured',models.BooleanField(default=False)),('sort_order',models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name='Enquiry', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('phone',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('message',models.TextField(blank=True)),('status',models.CharField(choices=[('NEW','New'),('CONTACTED','Contacted'),('CONVERTED','Converted'),('CLOSED','Closed')],default='NEW',max_length=20)),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.product'))]),
        migrations.CreateModel(name='Order', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('phone',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('address',models.TextField(blank=True)),('notes',models.TextField(blank=True)),('quantity',models.PositiveIntegerField(default=1)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('status',models.CharField(choices=[('BOOKED','Booked'),('CONFIRMED','Confirmed'),('READY','Ready'),('DELIVERED','Delivered'),('CANCELLED','Cancelled')],default='BOOKED',max_length=20)),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.product'))]),
        migrations.CreateModel(name='Sale', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('invoice_no',models.CharField(max_length=50,unique=True)),('customer_name',models.CharField(max_length=150)),('phone',models.CharField(blank=True,max_length=30)),('quantity',models.PositiveIntegerField(default=1)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('payment_mode',models.CharField(choices=[('Cash','Cash'),('UPI','UPI'),('Card','Card'),('Bank','Bank Transfer'),('Credit','Credit')],default='Cash',max_length=30)),('sale_date',models.DateField()),('notes',models.TextField(blank=True)),('customer',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.customer')),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.product'))]),
        migrations.CreateModel(name='Purchase', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('bill_no',models.CharField(max_length=50,unique=True)),('supplier_name',models.CharField(max_length=150)),('quantity',models.PositiveIntegerField(default=1)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('purchase_date',models.DateField()),('notes',models.TextField(blank=True)),('supplier',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.supplier')),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='showroom.product'))]),
        migrations.CreateModel(name='Expense', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('date',models.DateField()),('category',models.CharField(choices=[('Rent','Rent'),('Salary','Salary'),('Transport','Transport'),('Electricity','Electricity'),('Marketing','Marketing'),('Repair','Repair'),('Other','Other')],default='Other',max_length=40)),('description',models.CharField(max_length=220)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('payment_mode',models.CharField(default='Cash',max_length=30))]),
        migrations.CreateModel(name='LedgerEntry', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('date',models.DateField()),('entry_type',models.CharField(choices=[('CREDIT','Credit'),('DEBIT','Debit')],max_length=10)),('account',models.CharField(max_length=150)),('reference',models.CharField(blank=True,max_length=100)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('narration',models.TextField(blank=True))]),
        migrations.CreateModel(name='Offer', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('title',models.CharField(max_length=180)),('title_hi',models.CharField(blank=True,max_length=180)),('description',models.TextField(blank=True)),('description_hi',models.TextField(blank=True)),('discount_text',models.CharField(blank=True,max_length=100)),('valid_until',models.DateField(blank=True,null=True)),('image_data',models.TextField(blank=True)),('published',models.BooleanField(default=True)),('product',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='offers',to='showroom.product'))]),
        migrations.CreateModel(name='ServiceQuery', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('mobile',models.CharField(max_length=30)),('query',models.TextField(blank=True)),('category',models.CharField(choices=[('GENERAL','General Service'),('REPAIR','Repair'),('BATTERY','Battery'),('CHARGER','Charger'),('MOTOR','Motor'),('ELECTRICAL','Electrical'),('WARRANTY','Warranty'),('SPARES','Spare Parts'),('OTHER','Other')],default='GENERAL',max_length=30)),('vehicle_model',models.CharField(blank=True,max_length=150)),('preferred_date',models.DateField(blank=True,null=True)),('priority',models.CharField(choices=[('LOW','Low'),('MEDIUM','Medium'),('HIGH','High'),('URGENT','Urgent')],default='MEDIUM',max_length=10)),('status',models.CharField(choices=[('NEW','New'),('ASSIGNED','Assigned'),('IN_PROGRESS','In Progress'),('WAITING','Waiting for Customer'),('RESOLVED','Resolved'),('CLOSED','Closed')],default='NEW',max_length=20)),('ticket_no',models.CharField(blank=True,max_length=30,unique=True)),('internal_notes',models.TextField(blank=True))]),
        migrations.CreateModel(name='SupportQuery', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('name',models.CharField(max_length=150)),('mobile',models.CharField(max_length=30)),('query',models.TextField(blank=True)),('category',models.CharField(choices=[('PRODUCT','Product Information'),('ORDER','Order / Booking'),('PAYMENT','Payment'),('DELIVERY','Delivery'),('WARRANTY','Warranty'),('SERVICE','Service'),('SPARES','Spare Parts'),('COMPLAINT','Complaint'),('OTHER','Other')],default='PRODUCT',max_length=30)),('order_number',models.CharField(blank=True,max_length=50)),('priority',models.CharField(choices=[('LOW','Low'),('MEDIUM','Medium'),('HIGH','High'),('URGENT','Urgent')],default='MEDIUM',max_length=10)),('status',models.CharField(choices=[('NEW','New'),('ASSIGNED','Assigned'),('IN_PROGRESS','In Progress'),('WAITING','Waiting for Customer'),('RESOLVED','Resolved'),('CLOSED','Closed')],default='NEW',max_length=20)),('ticket_no',models.CharField(blank=True,max_length=30,unique=True)),('internal_notes',models.TextField(blank=True))]),
    ]
